apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scanner-service-policy
  namespace: vuln-alert
spec:
  podSelector:
    matchLabels:
      app: scanner-service
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53